/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  // Safelist for classes that might be dynamically generated
  safelist: [
    // Keep any classes that might be dynamically generated
    'text-green-500',
    'text-blue-600',
    'text-purple-600',
    'text-gray-900',
    'text-gray-600',
    'text-gray-700',
    'text-white',
    'bg-white',
    'bg-gray-50',
    'bg-blue-600',
    'bg-purple-600',
    'border-white',
    'border-2',
    'hover:bg-gray-100',
    'hover:bg-white',
    'hover:text-blue-600',
    'transition-colors',
    'rounded-lg',
    'rounded-full',
    'shadow-lg',
    'object-cover',
    'w-64',
    'h-64',
    'w-4',
    'h-4',
    'w-6',
    'h-6',
    'w-8',
    'h-8',
    'w-12',
    'h-12',
    'w-16',
    'h-16',
    'w-20',
    'h-20',
    'w-24',
    'h-24',
    'w-32',
    'h-32',
    'w-40',
    'h-40',
    'w-48',
    'h-48',
    'w-56',
    'h-56',
    'w-64',
    'h-64',
    'w-72',
    'h-72',
    'w-80',
    'h-80',
    'w-96',
    'h-96'
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        }
      },
      // Ensure focus styles are visible
      ringColor: {
        DEFAULT: '#3b82f6',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}